name: Build and Test Flutter App
on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

      # Build for Android
      # - run: flutter build apk

      # Build for macOS
      # - run: flutter build macos

      # Build for Windows
      # - run: flutter build windows

      # Build for Linux
      - run: flutter build linux

      # Upload APK as a build artifact
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: app-release-apk
      #     path: build/app/outputs/flutter-apk/app-release.apk

      # Upload macOS app as a build artifact
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: macos-release-app
      #     path: build/macos/Build/Products/Release/*.app

      # Upload Windows app as a build artifact
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: windows-release-app
      #     path: build/windows/runner/Release/*.exe

      # Upload Linux app as a build artifact
      - uses: actions/upload-artifact@v2
        with:
          name: linux-release-app
          path: build/linux/x64/release/bundle/*
