name: Build and Test Flutter App
on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build ios --no-codesign

      # Upload iOS build as a build artifact
      - uses: actions/upload-artifact@v2
        with:
          name: app-release-ios
          path: build/ios/iphoneos/Runner.app

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build linux

      # Upload Linux build as a build artifact
      - uses: actions/upload-artifact@v2
        with:
          name: app-release-linux
          path: build/linux/x64/release/bundle

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build windows

      # Upload Windows build as a build artifact
      - uses: actions/upload-artifact@v2
        with:
          name: app-release-windows
          path: build/windows/runner/Release
